#!/bin/bash

spinner() {
    local pid=$!
    local delay=0.1
    local spin='|/-\'
    while kill -0 $pid 2>/dev/null; do
        for i in $(seq 0 3); do
            printf "\r[%c] Processando..." "${spin:$i:1}"
            sleep $delay
        done
    done
    printf "\r[✔] Concluído!        \n"
}

(sleep 3) $ spinner
